name: CD

on:
  push:
    branches:
      - main
    tags:
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/syn/apps/todo_node_api
            git pull origin main
            git status
            npm install --omit=dev
            echo test
            pm2 restart todo --update-env